url: https://treasure-island-therapy.github.io
# baseurl: /treasure-island-therapy/

# Site settings
title: Treasure Island Therapy
email: therapy2ti@gmail.com
description: "Treasure Island Therapy, for educational and therapy needs of children, based in Pune. Material for Occupational Therapy, Speech Therapy, Special Education for children with Autism, Down'"


# Team names, titles and social links
people:
- name: Ebrahim Chasmai
  pic: 1
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Tahera Chasmai
  pic: 2
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/people/Treasure-Island-Therapy/100063803840120/

# Postal address (add as many lines as necessary)
address:
  - line: A-32, KPCT, Fatimanagar
  - line: Wanowrie, Pune, Maharashtra

# Build settings
markdown: kramdown
permalink: pretty